INSERT INTO COMPANY (ID, NAME) VALUES (1, 'IBM');
INSERT INTO COMPANY (ID, NAME) VALUES (2, 'APPLE');
INSERT INTO USER (ID, LOGIN, COMPANY_ID) VALUES (1, 'JOHNDOE', 1);
INSERT INTO USER (ID, LOGIN, COMPANY_ID) VALUES (2, 'JANE', 1);
INSERT INTO USER (ID, LOGIN, COMPANY_ID) VALUES (3, 'RICK', 2);
