CREATE TABLE COMPANY
(
	ID NUMBER(19) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
);

CREATE TABLE USER
(
	ID NUMBER(19) NOT NULL,
	LOGIN VARCHAR2(50) NOT NULL,
	COMPANY_ID VARCHAR2(50) NOT NULL REFERENCES COMPANY(ID)
);
